### ISSUE TITLE
this script don't work for me

### ISSUE THREAD

**Issue by d1Nca** [VORPCORE/vorp_mining#14]
Hello guys, this script don't work for me or I don't know how to use it...
I also went to the mine in Annesburg, I can't use it Pickaxe...i also put in mysql usable 0 to 1 and don't work...
on my inventory i have Pickaxe but is not working doubleclick to use them...
no error, server.cfg is configuring with syn_minigame and vorp_mining
Can you help me?

**Comment by outsider31000** [comment]
its not usable all you need is to have the item in your imventory, you need to search where the promt is to mine

**Comment by d1Nca** [comment]
yes, in the end I noticed how it can be mined....me inside the mine that is for such a thing and nothing happens, I didn't think that it is mined in the field.
